---
title: "Bilanse-aneks"
author: "Iwo Augustyński"
date: "11 czerwca 2017"
output: html_document
---

Źródło danych: Eurostat (nama_10_gdp)
</br>
</br>
Ujemny bilans zagranicy na wykresie ma charakter finansowy, "pieniężny". Oznacza nadwyżkę eksportu nad importem danego kraju. Zagranica bierze towary i usługi "na kreskę" czyli zwiększając swój dług. Kraj gromadzi go w formie np. rezerw walutowych w banku centralnym. W ten sposób część oszczędności krajowych ma formę długu zagranicznego i może zastępować dług krajowy. 
Nadwyżka w handlu zagranicznym umożliwa zatem redukcję długu publicznego (zobacz przykład Irlandii - IE) ale kosztem większej podatności na ryzyka globalne (ryzyko kursowe, ryzyko polityczne w krajach partnerskich itp.)
</br>
</br>

###Aneks rachunkowy

</br>
Zgodnie z systemem rachunków narodowych PKB [(ESA2010)](http://stat.gov.pl/download/gfx/portalinformacyjny/pl/defaultaktualnosci/5526/5/1/3/esa2010_pl.pdf) jest obliczane na trzy sposoby. 

1. Od strony wydatkowej:

       |      |
-------- |--------
**PKB**  | = **C** konsumpcja 
        <br> | + **G** wydatki publiczne
       <br>  | + **I** inwestycje w kapitał trwały
        <br> | + **I** zmiana zapasów
        <br> | + **E** eksport
        <br> | - **Im** import
        <br> | <br>

2. Od strony dochodowej:

       |      |
-------- |--------|
**PKB** | = **D** dochody z pracy |
      <br>  | + **A** zatrzymane zyski przedsiębiorstw (nadwyżka operacyjna brutto) |
      <br>  | + **T** podatki od produkcji i importu |

</br>
Oba podejścia muszą dać taki sam wynik co można zapisać następująco:

**D + A + T = C + G + I + E - Im**     co po przekształceniu daje

**(D + A) - (C + I) = (G - T) + (E - Im)** czyli

dochody - wydatki sektora prywatnego = (dochody - wydatki sektora publicznego) + (wydatki - dochody sektora zagranicy)

Dla przypomnienia - eksport z danego kraju oznacza, że zagranica kupuje, czyli jest to jej wydatek. Import do danego kraju oznacza natomiast, że zagranica sprzedaje, dlatego jest to jej dochód.

</br>
</br>
</br>