---
title: "Czy można zlikwidować dług publiczny?"
author: "Iwo Augustyński"
date: "31 maja 2017"
output: html_document
---

# Problem bilansów sektorowych
<br>
Problem wielkości i konsekwencji wzrostu długu publicznego jest chyba jednym z najczęściej
dyskutowanych zagadnień ekonomicznych. Co roku choćby paliwa do kolejnych komentarzy dolewają
informacje o planowanym na kolejny rok budżecie państwa. 

Wydaje się, że generalnie panuje zgoda co do szkodliwości deficytu i długu publicznego (w końcu 
jest o tym nawet wzmianka w konstytucji) a dyskusje dotyczą raczej skali szkód.

Jak jednak udowadniam poniżej jest to pogląd błędny.


<br>

Krótkie wyjaśnienie podstawowych faktów:

1. Każda forma oszczędności jest zobowiązaniem ('długiem')
kogoś innego. Gdy gospodarstwo domowe oszczędza kupując
obligacje skarbowe --- nabywa dług państwa. Gdy oszczędza
kupując akcje na Giełdzie Papierów Wartościowych --- nabywa
zobowiązania sektora prywatnego (np. PKN Orlen). Gdy
oszczędza 'na koncie' --- nabywa zobowiązania sektora
bankowego. Gdy 'trzyma gotówkę' (PLN) --- nabywa
zobowiązania banku centralnego. Gdy 'trzyma dolary' ---
nabywa zobowiązania USA.

2. Oszczędzanie poprzez zakup złota, nieruchomości, zabytkowych aut, znaczków
itp. itd. są traktowane jako inwestycje i oznaczają wydatki sektora prywatnego (realizowane
głównie wewnątrz tego sektora, ale również dotyczące zagranicy - import dzieł sztuki, lub państwa - prywatyzacja).

3. Jeśli oszczędności gospodarstw domowych są większe niż
ich długi, to ta nadwyżka może być trzymana w formie długu
przedsiębiorstw (w tym banków), państwa lub zagranicy. Innej
opcji nie ma.

4. To samo tyczy się innych sektorów. Jeśli przedsiębiorstwa
generują oszczędności netto (lub ich potrzeby inwestycyjne
nie są w stanie wchłonąć całych oszczędności gospodarstw
domowych), to znaczy że muszą nabyć czyjeś
zobowiązania. Jest kilka opcji --- zobowiązania gospodarstw
domowych, państwa lub zagranicy.

5. W państwach rozwiniętych sektor prywatny (gospodarstwa
domowe + przedsiębiorstwa, w tym banki) osiąga zazwyczaj
nadwyżkę oszczędności. W jaki sposób ulokować te nadwyżki?
Są dwie opcje --- dług publiczny lub zagraniczny.

6. Co to jest dług zagraniczny? Aby powstał zagranica (inne
państwa razem wzięte) musi go najpierw wyemitować. Kiedy ma
to miejsce? Odpowiedź jest prosta --- gdy inne państwa muszą
zadłużyć się aby kupić 'od nas' więcej, niż w danej chwili
sprzedają 'nam', tj. gdy mamy tzw. dodatnie saldo bilansu
handlowego. Innymi słowy, aby sektor prywatny 'gromadził'
dług zagranicy, gospodarka musi więcej eksportować niż
importować.

7. Co w sytuacji gdy eksport jest równy importowi? Jeśli
sektor prywatny nadal chce oszczędzać, zostaje mu jedna
opcja --- musi nabywać zobowiązania państwa
(tzw. obligacje). Nadwyżka sektora prywatnego przyjmuje
formę długu publicznego.

8. Jeśli dany kraj posiada ujemny bilans handlowy, to dług
publiczny nie tylko musi 'pokryć' oszczędności sektora
prywatnego, ale rówież sfinansować deficyt handlowy.

<br>

To wszystko wynika z działań matematycznych/księgowych a nie
takiej czy innej teorii ekonomicznej.

Poniżej możecie zweryfikować te informacje.
